### PR TITLE
Fix ember version detection

### PR DESCRIPTION
**Pull request by akatov**
a rebased version of #556 with passing tests.
fixes #556

### CODE REVIEW

**Comment by akatov** [comment]
@ivanvanderbyl I hope you're ok with me using your work here :-)

**Comment by ivanvanderbyl** [comment]
@akatov looks good to me, let's get this fixed :)

**Comment by ef4** [comment]
Thanks!

**Comment by ef4** [comment]
I was dreading spending another hour figuring out why Travis wasn't passing, nice to see it all turn green with this merged. 💯

**Comment by akatov** [comment]
🎊 🎊 🎊

**Pull request merged**
