### PR TITLE
Remove a few jQuery usages and ES6-fy a few functions

### PR DESCRIPTION
**Pull request by cibernox**
The long term goal is to decouple liquid-fire from jQuery, but one step at a time.
The task would be much simpler if the addon does not support IE9. Is there an official support matrix?

### CODE REVIEW

**Comment by ef4** [comment]
Officially, the same as Ember's.  I don't think most animations actually run in IE9, but I still don't want to start throwing exceptions where we didn't before.

jQuery is also exposed as part of LF's public API for people implementing their own transitions (this.newElement is decorated by jQuery, analogous to `Ember.Component.prototype.$`. I ultimately want to sunset that whole api in favor of the work in ember-animated, but that will require more attention. ember-animated is careful to not leak jquery in any public API, although it is used in a few places internally.

**Comment by cibernox** [comment]
yeah, i figured that removing jQuery could be a titanic task, specially with IE9 support. Is ember-animated being actively developed?

**Comment by ef4** [comment]
Just need to find time to prioritize working on it.

**Comment by cibernox** [comment]
I forgot about this completely. Thanks!

**Comment by ef4** [comment]
I got it merged before its first birthday, that’s good right? 😝

**Pull request merged**
