### PR TITLE
Replace jquery usages with vanilla js

### LINKED ISSUE #673: Remove internal jquery usages
In `v0.34.0` (latest version) there is still necessary jquery as package, because liquid-fire is still using internal.

The goals is to replace it with vanilla js, so there is not anymore necessary to add jquery as dependency in the projects, which is using this packages.

All changes should be work on IE11+

### PR DESCRIPTION
**Pull request by mkszepp**
fix #673

### CODE REVIEW

**Comment by miguelcobain** [comment]
I tried this branch in my codebase and works great without jQuery. Thanks @mkszepp!
Hoping this gets merged.

**Comment by ef4** [comment]
@mkszepp please confirm your NPM username.

**Comment by mkszepp** [comment]
@ef4 i have now create a npm use & confirmed you invive in this repo

**Comment by mkszepp** [comment]
@miguelcobain v0.35.0 was released

@ef4 thank you!

**Pull request merged**
