### PR TITLE
Make jQuery a Dependency

### PR DESCRIPTION
**Pull request by jherdman**
Also bumps to ^1.1.0 which seems to resolve the `Ember.$` problem.

### CODE REVIEW

**Comment by ef4** [comment]
I don't think this is correct. We don't want to bring our own copy of `@ember/jquery`, we want to use the app's copy. We could say that by making it a peerDep, but because NPM's support for them is so bad nobody pays attention to peerDeps.

**Comment by jherdman** [comment]
Well, we could try it and perhaps just document that you need to "bring your own jQuery"?

**Comment by rwwagner90** [comment]
How much jQuery usage is there? It may be best to remove jQuery entirely.

**Comment by jherdman** [comment]
That's definitely the one-true solution. I was hoping to get something out soonish to help those attempting to upgrade to Octane. This is a bit of a blocker for my team.

**Comment by jherdman** [comment]
I've begun work on completely removing jQuery here #649

**Comment by ef4** [comment]
> I was hoping to get something out soonish to help those attempting to upgrade to Octane. This is a bit of a blocker for my team.

There is some major miscommunication happening here, because octane works 100% fine with `@ember/jquery` and `liquid-fire`.

Why do you think you need to remove jquery?

Before octane was released, there was a version of it that insisted on removing jquery, but because that blocked so many people's upgrades, the final released version of octane does not require dropping jquery.

**Comment by jherdman** [comment]
> Why do you think you need to remove jquery?

In my apps I've gutted jQuery completed, it's not listed in my `devDependencies`. This means liquid-fire is effectively bringing its own copy along. This copy leans upon `Ember.$`. If I upgrade `@ember/jquery` in liquid-fire this problem goes away.

**Comment by johanrd** [comment]
@jherdman I understand your goal here. Liquid-fire is a very large burden to bring into a project that does not already use jQuery.

I just want a simple and ergonomic way of animating between my routes. `<LiquidOutlet>` seems to be the perfect component, except for the very expensive bundle size of adding LiquidFire and jQuery.

I see examples where [ember-animated is being used to animate between routes](https://github.com/nickschot/emberconf2018/blob/master/app/templates/components/mobile-page.hbs), although it does not seem as ergonomic. Do you perhaps know of any other alternatives?

**Pull request closed without merging**
