### PR TITLE
Update to leverage `@glimmer/env` for debug code stripping.

### PR DESCRIPTION
**Pull request by rwjblue**
I used this as an example in http://rwjblue.com/2017/05/01/enabling-debug-code-stripping/, figured I should PR it too 😺...

### CODE REVIEW

**Comment by ef4** [comment]
Haha, I read your example and I suspected you would. 

How far back in ember versions does this work?

**Comment by ef4** [comment]
(I guess travis is telling me "lots")

**Comment by rwjblue** [comment]
The real work is being done by the transpilation of the addon (which comes from your direct dependency  on ember-cli-babel@6.1). I've tested ember-cli-babel@6 with Ember CLI's as old as 2.2.0...

**Comment by ef4** [comment]
Transpilation for the win.

**Pull request merged**
