### PR TITLE
Remove named outlets in Ember 4+

### PR DESCRIPTION
**Pull request by rwwagner90**

### CODE REVIEW

**Comment by ef4** [comment]
I pushed some commits here that make this nearly complete. 

There are a couple more tests and places in the dummy app that are using named outlets.

**Comment by rwwagner90** [comment]
@ef4 I just totally removed the `{{liquid-outlet "test"}}` is that the correct fix?

**Comment by rwwagner90** [comment]
We have to skip the model-dependent test, but everything else seems to pass with that named outlet just totally removed. I couldn't find a `treeFor` that seemed to work for tests, but if there is one we could conditionally include it.

**Comment by ef4** [comment]
Thanks @rwwagner90, this is ready to go.

**Pull request merged**
