### PR TITLE
WIP: Canary Support

### PR DESCRIPTION
**Pull request by wagenet**
Includes some significant breaking changes.

### CODE REVIEW

**Comment by rwjblue** [comment]
FWIW, the `id` error is also present in the 2.8.0-beta series.

**Comment by johanbove** [comment]
Thanks first of all for all the hard work on this addon;

I'm however a little confused with the commit by ©wagenet: a979937 "remove support for modals" : does this mean that liquid-fire as of version 0.24.1 really no longer supports modals? I'm starting out with Liquid-fire in a new project and we liked the "modals" feature, so this is a little confusing without extra background information.

**Comment by Cryrivers** [comment]
@johanbove as changelog mentioned, `BREAKING: Removed liquid-modal. It used too much private API and ember-elsewhere is a superior alternative that composes nicely with liquid-fire.`

So I guess you need to start planning to remove `liquid-modal`s.

**Comment by johanbove** [comment]
Thank you @Cryrivers. Was looking at the current documentation and there is no mention of the deprecation of "liquid-modal" there yet. If there is no issue for this yet, I'll create one.

**Comment by chrism** [comment]
Hi @johanbove — I can understand the surprise, I was a little bit confused too.

Honestly, though the ember elsewhere implementation is really great and does make more sense than the modals in liquid fire. I wrote this blog post explaining the steps I took to migrate from one to the other, I hope it might be some help for you.

https://medium.com/@chrisdmasters/migrating-from-liquid-fire-modals-to-ember-elsewhere-modals-in-ember-js-9f7142ff1dec

**Pull request merged**
