### PR TITLE
Brand Design

### PR DESCRIPTION
**Pull request by ryannmack**
I know many developers' lives that are made easier by using Liquid Fire. Here is my contribution, as a designer. The name, "Liquid Fire", inspired me to make this the first brand for my [Open Source Branding][osb] project.

<p align="center">

</p>

If you would like to collaborate on this brand feel free to open issues or pull requests on [Open Source Branding's][osblf] repo.

The branding design, logo, typography, and icon are provided no strings attached<sup>1</sup> use it how ever you want, even commercially. 

<sup>1</sup> [Creative Commons Attribution 4.0 International License][cc]. Attribution of any kind would be appreciated.

## Icons

| png  | svg |
| ------------- | ------------- |
| [![liquid fire color icon][image1png]][image1png]  | [![liquid fire color icon][image1svg]][image1svg] |
| [![liquid fire grayscale icon][image2png]][image2png]  | [![liquid fire grayscale icon][image2svg]][image2svg] |

## Color Variations

[![liquid fire color variations][cv]][cv]

## Sketch File Dowload

[![sketchicon] liquid-fire-icon-design.sketch][sketchdoc]

[osb]: https://github.com/ryannpierce/open-source-branding
[osblf]: https://github.com/ryannpierce/open-source-branding/tree/master/liquid-fire
[cc]: https://creativecommons.org/licenses/by/4.0/
[image1png]: https://raw.githubusercontent.com/ryannpierce/open-source-branding/4dba3389b7def5b4332bac61b828b3caa7051307/liquid-fire/liquid-fire_color-icon.png
[image1svg]: https://rawgit.com/ryannpierce/open-source-branding/4dba3389b7def5b4332bac61b828b3caa7051307/liquid-fire/liquid-fire_color-icon.svg
[image2png]: https://raw.githubusercontent.com/ryannpierce/open-source-branding/4dba3389b7def5b4332bac61b828b3caa7051307/liquid-fire/liquid-fire_grayscale-icon.png
[image2svg]: https://rawgit.com/ryannpierce/open-source-branding/4dba3389b7def5b4332bac61b828b3caa7051307/liquid-fire/liquid-fire_grayscale-icon.svg
[cv]: https://raw.githubusercontent.com/ryannpierce/open-source-branding/4dba3389b7def5b4332bac61b828b3caa7051307/liquid-fire/liquid-fire_concepts.png
[sketchicon]: https://raw.githubusercontent.com/ryannpierce/open-source-branding/4dba3389b7def5b4332bac61b828b3caa7051307/misc/sketch-icon.png
[sketchdoc]: https://github.com/ryannpierce/open-source-branding/raw/4dba3389b7def5b4332bac61b828b3caa7051307/liquid-fire/liquid-fire-icon-design.sketch

### CODE REVIEW

**Comment by ef4** [comment]
Oh yay, thanks!

**Comment by marcemira** [comment]
Nice!! :heart_eyes:

**Comment by oriSomething** [comment]
the logo is nice. i have issues with the typography

**Comment by ryannpierce** [comment]
Ping @ef4, let me know if you want to discuss any changes for the logo. Or if you don't want to use the logo, feel free to close this pull request.

**Comment by ef4** [comment]
Hey @ryannpierce, thanks for offering to put in more work on this. I will open a discussion on [your repo](https://github.com/ryannpierce/open-source-branding/issues).

**Pull request closed without merging**
