### PR TITLE
Fix ember-component.send-action deprecation introduced in ember 3.4

### LINKED ISSUE #618: send-action deprecation on Ember 3.4
See https://emberjs.com/deprecations/v3.x#toc_ember-component-send-action for more details.

>
 Log: |
            { type: 'warn',
              text:
               '\'DEPRECATION: You called <my-component@component:liquid-child::ember27446>.sendAction("liquidChildDidRender") but Component#sendAction is deprecated. Please use closure actions instead. [deprecation id: ember-component.send-action] See https://emberjs.com/deprecations/v3.x#toc_ember-component-send-action for more details.\\n        at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:25070:29)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:25172:17)\\n        at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:25094:17)\\n        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:25172:17)\\n        at invoke (http://localhost:7357/assets/vendor.js:25181:17)\\n        at deprecate (http://localhost:7357/assets/vendor.js:25153:34)\\n        at Class.sendAction (http://localhost:7357/assets/vendor.js:66425:49)\\n        at _waitForAll.then (http://localhost:7357/assets/vendor.js:229967:16)\\n        at tryCatcher (http://localhost:7357/assets/vendor.js:71728:21)\'\n' }

### PR DESCRIPTION
**Pull request by scottkidder**
Fixes #618 

Not sure if extra work needs to be to keep backwards compat.

### CODE REVIEW

**Comment by wagenet** [comment]
Doesn't look like the CI failure is related. @ef4 can you restart it?

**Comment by scottkidder** [comment]
I appear to be on Travis's bad side...

**Comment by scottkidder** [comment]
:crossed_fingers:

**Comment by ef4** [comment]
Thanks, this is released in 0.29.4.

**Pull request merged**
