### PR TITLE
Remove lf-outlet as it is undefined

### PR DESCRIPTION
**Pull request by wagenet**
StaticOutlet doesn't exist.

### CODE REVIEW

**Comment by wagenet** [comment]
Looks like the failures are not related to this change.

**Comment by ef4** [comment]
Yes, the test failure was because the new beta series has a private API change that we'll need to match.

Thanks for the PR, sorry this broke your build!

**Comment by wagenet** [comment]
No problem! This would have broken for anyone trying to require this file, just no one was! Only I was since I was doing a sort of require-all!

**Comment by wagenet** [comment]
Wow, that was a lot of exclamation points :)

**Pull request merged**
